# Generated by Django 3.2.23 on 2024-02-02 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('name_area', models.CharField(max_length=200, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id_brigade', models.AutoField(primary_key=True, serialize=False)),
                ('name_brigade', models.CharField(max_length=200, verbose_name='Название бригады')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер')),
                ('chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_of_brigades', to=settings.AUTH_USER_MODEL, verbose_name='Главный бригадир')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id_contract', models.AutoField(primary_key=True, serialize=False)),
                ('name_contract', models.TextField(max_length=200, verbose_name='Имя')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.area', verbose_name='Участок')),
                ('brigade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.brigade', verbose_name='Бригада')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('name_service', models.CharField(max_length=200, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('base_price', models.DecimalField(decimal_places=2, default=1500, max_digits=10)),
                ('alarm_system_discount', models.DecimalField(decimal_places=2, default=20, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('name_status', models.CharField(max_length=200, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(verbose_name='Продолжительность (в месяцах)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('duration', models.CharField(blank=True, max_length=25, null=True)),
                ('comments', models.TextField(blank=True)),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость')),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.area')),
                ('assigned_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.brigade', verbose_name='Назначенная бригада')),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_for_brigade', to='main.brigade')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service')),
                ('status', models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='main.status', verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='tariffs',
            field=models.ManyToManyField(related_name='services', to='main.Tariff', verbose_name='Тарифы'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id_schedule', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateField(verbose_name='Начало периода')),
                ('end', models.DateField(verbose_name='Конец периода')),
                ('task_description', models.TextField(verbose_name='Описание задачи')),
                ('assigned_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Назначенный работник')),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brigade', verbose_name='Бригада')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id_report', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('number', models.IntegerField(verbose_name='Число')),
                ('description', models.TextField(verbose_name='Описание')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.area', verbose_name='Участок')),
                ('service_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.servicerequest', verbose_name='Заявка на услугу')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id_receipt', models.AutoField(primary_key=True, serialize=False)),
                ('date_receipt', models.DateTimeField(verbose_name='Дата')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('seller_details', models.IntegerField(verbose_name='Реквизиты продавцы')),
                ('payment_type', models.CharField(max_length=200, verbose_name='Тип оплаты')),
                ('number_receipt', models.IntegerField(verbose_name='Номер')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contract', verbose_name='Контракт')),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.service', verbose_name='Услуга')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.status', verbose_name='Статус')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='MemberBrigade',
            fields=[
                ('id_member_brigade', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brigade', verbose_name='Бригада')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'unique_together': {('user', 'brigade')},
            },
        ),
    ]
