# Generated by Django 3.2.23 on 2024-02-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='id_report',
        ),
        migrations.AlterField(
            model_name='report',
            name='number',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Число'),
        ),
    ]
