# Generated by Django 3.2.23 on 2024-02-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240205_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='area',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
    ]
