# Generated by Django 4.2.7 on 2024-03-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_notificationsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='message',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='status_code',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
