# Generated by Django 5.0 on 2024-04-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_servicerequest_card_number_servicerequest_cvv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='status',
        ),
    ]
