# Generated by Django 5.0 on 2024-04-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_receipt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='receipt',
            name='last_4_digits',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Последние 4 цифры карты'),
        ),
    ]
