# Generated by Django 5.0 on 2024-04-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_receipt_payment_type_receipt_last_4_digits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='last_4_digits',
        ),
        migrations.AddField(
            model_name='receipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10, verbose_name='Сумма оплаты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='card_number',
            field=models.CharField(default=1, max_length=16, verbose_name='Номер карты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='cvv',
            field=models.CharField(default=0, max_length=3, verbose_name='CVV-код'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='expiry_date',
            field=models.CharField(default=1, max_length=7, verbose_name='Срок действия карты'),
            preserve_default=False,
        ),
    ]
