# Generated by Django 5.0 on 2024-04-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_receipt_last_4_digits_receipt_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='expiry_date',
            field=models.CharField(default='ММ/ГГГГ', max_length=7, verbose_name='Срок действия карты'),
        ),
    ]
