# Generated by Django 5.0 on 2024-04-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_receipt_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='number_receipt',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='seller_details',
        ),
    ]
