# Generated by Django 5.0 on 2024-04-11 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_receipt_number_receipt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='amount',
            new_name='total_amount',
        ),
    ]
