# Generated by Django 5.0 on 2024-04-11 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_amount_receipt_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='expiry_date',
        ),
    ]
