# Generated by Django 5.0 on 2024-04-11 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_servicerequest_card_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='expiry_date',
        ),
    ]
