# Generated by Django 5.0 on 2024-04-11 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_total_amount_receipt_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='total_price',
            new_name='total_amount',
        ),
    ]
