# Generated by Django 5.0 on 2024-04-11 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_total_price_receipt_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='id_receipt',
            new_name='id',
        ),
    ]
