# Generated by Django 5.0 on 2024-04-11 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_id_receipt_receipt_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='sum',
        ),
    ]
