# Generated by Django 5.0.4 on 2024-04-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_receipt_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='work_days',
            field=models.IntegerField(default=0, verbose_name='Отработанные дни'),
        ),
    ]
