# Generated by Django 5.0 on 2024-04-16 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_event_delete_weeklyschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.servicerequest', verbose_name='Заявка на услугу'),
        ),
    ]
