# Generated by Django 5.0.4 on 2024-04-20 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_schedule_service_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Время начала')),
                ('task_description', models.TextField(verbose_name='Описание задачи')),
                ('assigned_members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Назначенные работники')),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brigade', verbose_name='Бригада')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.servicerequest', verbose_name='Заявка на услугу')),
            ],
        ),
    ]
