# Generated by Django 5.0.6 on 2024-05-31 17:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedulemember',
            unique_together={('user', 'date')},
        ),
    ]
