# Generated by Django 5.0.6 on 2024-06-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_memberbrigade_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memberbrigade',
            unique_together=set(),
        ),
    ]
