# Generated by Django 5.0.6 on 2024-06-02 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_brigade_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='brigade',
        ),
    ]
