# Generated by Django 5.0.6 on 2024-06-03 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_servicerequest_brigade'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemember',
            name='service_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.servicerequest'),
            preserve_default=False,
        ),
    ]
